[package]
name = "libphoenix"
version = "0.1.0"
authors = ["Jeremy Davis <jeremydavis519@gmail.com>"]
edition = "2018"

[dependencies]

[features]
default = ["global-allocator"]

global-allocator = []
kernelspace = []
no-start = []
profiler = []
