[package]
name = "virtio-gpu"
version = "0.1.0"
authors = ["Jeremy Davis <jeremydavis519@gmail.com>"]
edition = "2018"

#[lib]
#name = "virtio_gpu"
#crate-type = ["staticlib"]

[dependencies]
libdriver = { path = "../../libdriver" }
libphoenix = { path = "../../../libphoenix" }
